### ISSUE TITLE
Several pages have wrong images

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/ems-docs#10]
Somehow, somewhere, they got changes accidentally to link the wrong image inline. For example step 2 on https://ems-docs.element.io/Get-Your-Own-EMS-Server.html or step 9 on https://ems-docs.element.io/EMS-Server-With-Custom-Domain.html

There may be more

**Comment by uhoreg** [comment]
step to on https://ems-docs.element.io/Check-Status.html also seems to be an incorrect image

**Comment by Twi1ightSparkle** [comment]
Yep. All the incorrect images will (should) get fixed by https://github.com/vector-im/ems-docs/pull/19
